name: tbls

on:
  workflow_dispatch:

jobs:
  update-tbls-docs:
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: sail
      DB_PASSWORD: pasword
    steps:
      - name: Create Database
        run: |
          sudo systemctl start mysql.service
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Create test table
        run: |
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USERNAME -p$DB_PASSWORD $DB_DATABASE -e "CREATE TABLE IF NOT EXISTS test (id INT PRIMARY KEY, name VARCHAR(255));"
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Generate DB schema document
        run: tbls doc -f mysql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST/$DB_DATABASE
