name: tbls

on:
  workflow_dispatch:

jobs:
  update-tbls-docs:
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testdb
      DB_USERNAME: root
      DB_PASSWORD: root
    # services:
    #   mysql:
    #     image: mysql:8.0
    #     env:
    #       MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    #       MYSQL_DATABASE: $DB_DATABASE
    #       MYSQL_USER: $DB_USERNAME
    #       MYSQL_PASSWORD: $DB_PASSWORD
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Create Database
        run: |
          sudo systemctl start mysql.service
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Create test table
        run: |
          mysql -h $DB_HOST --port $DB_PORT -u $DB_USERNAME -p$DB_PASSWORD $DB_DATABASE -e "CREATE TABLE IF NOT EXISTS test (id INT PRIMARY KEY, name VARCHAR(255));"
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Generate DB schema document
        run: tbls doc -f
